core-contracts/Reserve/src/main/java/network/balanced/score/core/Checks.java
core-contracts/Reserve/src/main/java/network/balanced/score/core/ReserveFund.java

disburse and claim method added in reserve fund contract

added disburse in reseerve

---

build.gradle
core-contracts/Multicall/build.gradle
core-contracts/Multicall/src/main/java/network/balanced/score/core/multicall/Multicall.java
core-contracts/Multicall/src/test/java/network/balanced/score/core/multicall/DexMock.java
core-contracts/Multicall/src/test/java/network/balanced/score/core/multicall/MulticallTest.java
settings.gradle

Aggregate multiple dex calls in one single method. This contract can be used to aggregate other readonly methods in future.

New multicall contract

---

core-contracts/Reserve/build.gradle

Set version and contract address for reserve contract

Set version to 0.1.0 for reserve contract

---

.github/workflows/pr-test.yml
.github/workflows/push-main.yml
README.md

Includes basic pipelines to build the containers.  Need guidance if we should build a Makefile or simply run the test commands all from within the CI workflow.

Initialize CI

---

core-contracts/DAOfund/src/main/java/network/balanced/score/core/daofund/DAOfundImpl.java
core-contracts/DAOfund/src/test/java/network/balanced/score/core/daofund/DAOfundImplTest.java
score-lib/src/main/java/network/balanced/score/lib/interfaces/DAOfund.java
score-lib/src/main/java/network/balanced/score/lib/structs/DisbursementString.java

Temporary change to fix the vote execution
Revert [this commit](0292c93d2d818bbde72b9382da33833cb89f809e) after fixing the issue.

Change disbursement amount to string

---

core-contracts/Dividends/src/main/java/network/balanced/score/core/dividends/Constants.java
core-contracts/Dividends/src/main/java/network/balanced/score/core/dividends/DividendsImpl.java
core-contracts/Governance/src/intTest/java/network/balanced/score/core/governance/GovernanceIntegrationTest.java
core-contracts/Governance/src/main/java/network/balanced/score/core/governance/GovernanceConstants.java
core-contracts/Governance/src/main/java/network/balanced/score/core/governance/GovernanceImpl.java
core-contracts/Loans/src/main/java/network/balanced/score/core/loans/LoansImpl.java
core-contracts/Loans/src/main/java/network/balanced/score/core/loans/utils/LoansConstants.java
core-contracts/Rewards/src/main/java/network/balanced/score/core/rewards/DataSourceImpl.java
core-contracts/Rewards/src/main/java/network/balanced/score/core/rewards/RewardsImpl.java
core-contracts/Rewards/src/test/java/network/balanced/score/core/rewards/RewardsTestContinuousRewards.java
score-lib/src/main/java/network/balanced/score/lib/utils/Constants.java

Using U_SECONDS_DAY from score-lib folder.

Constants from score-lib

---

.github/workflows/push-main.yml
data/config/genesis.json
data/config/governance/__init__.py
data/config/governance/governance.py
data/config/governance/network_proposal.py
data/config/governance/package.json
data/config/icon.json
data/config/icon_config.json
data/dockerenv/iconee
data/godWallet.json
docker-compose.yml

added integration test in CI

---

.github/workflows/pr-test.yml
buildSrc/src/main/groovy/network/balanced/gradle/plugin/DeployBalancedContracts.groovy
buildSrc/src/main/java/network/balanced/gradle/plugin/DefaultICONClient.java
buildSrc/src/main/java/network/balanced/gradle/plugin/utils/NameMapping.java
buildSrc/src/main/resources/contracts-sample.json
core-contracts/Multicall/build.gradle
core-contracts/StakedLP/build.gradle
util-contracts/DummyOracle/build.gradle
util-contracts/DummyOracle/src/main/java/network/balanced/score/util/dummyoracle/DummyOracle.java

Check if all contracts are deployable in CI

Add check for contract deployment

---

core-contracts/Dividends/src/intTest/java/network/balanced/score/core/dividends/DividendsIntegrationTest.java

run time reduced for dividends integration test.

Dividends Integration Test Optimized

---

core-contracts/Rebalancing/src/main/java/network/balanced/score/core/rebalancing/RebalancingImpl.java

added default price threshold in rebalancing on_install

updated priceThreshold for rebalancing in on_install

---

buildSrc/src/main/java/network/balanced/gradle/plugin/utils/NameMapping.java
buildSrc/src/main/resources/contracts-sample.json
core-contracts/BalancedOracle/build.gradle
core-contracts/BalancedOracle/src/main/java/network/balanced/score/core/balancedoracle/BalancedOracleConstants.java
core-contracts/BalancedOracle/src/main/java/network/balanced/score/core/balancedoracle/BalancedOracleImpl.java
core-contracts/BalancedOracle/src/main/java/network/balanced/score/core/balancedoracle/EMACalculator.java
core-contracts/BalancedOracle/src/main/java/network/balanced/score/core/balancedoracle/TWAPCalculator.java
score-lib/src/main/java/network/balanced/score/lib/interfaces/BalancedOracle.java
score-lib/src/main/java/network/balanced/score/lib/utils/Math.java
settings.gradle

Removed unit test since they depend on new features from the multi collateral branch

Balanced oracle

---

core-contracts/Loans/src/main/java/network/balanced/score/core/loans/LoansImpl.java
core-contracts/Loans/src/main/java/network/balanced/score/core/loans/asset/Asset.java
core-contracts/Loans/src/main/java/network/balanced/score/core/loans/asset/AssetDB.java
core-contracts/Loans/src/test/java/network/balanced/score/core/loans/LoansTest.java
core-contracts/Reserve/src/intTest/java/network/balanced/score/core/reserve/ReserveIntegrationTest.java
core-contracts/Reserve/src/main/java/network/balanced/score/core/reserve/ReserveFund.java
core-contracts/Reserve/src/test/java/network/balanced/score/core/reserve/ReserveFundTest.java
score-lib/src/main/java/network/balanced/score/lib/interfaces/Loans.java
score-lib/src/main/java/network/balanced/score/lib/interfaces/Reserve.java

Also includes removal of dead markets #204

205 rework order of collateral redemption

---

core-contracts/BalancedOracle/src/main/java/network/balanced/score/core/balancedoracle/BalancedOracleImpl.java
core-contracts/BalancedOracle/src/test/java/network/balanced/score/core/balancedoracle/BalancedOracleTest.java
core-contracts/Governance/src/main/java/network/balanced/score/core/governance/GovernanceImpl.java
core-contracts/Governance/src/main/java/network/balanced/score/core/governance/VoteActions.java
core-contracts/Governance/src/test/java/network/balanced/score/core/governance/GovernanceTest.java
core-contracts/Governance/src/test/java/network/balanced/score/core/governance/GovernanceVotingTest.java
core-contracts/Loans/src/intTest/java/network/balanced/score/core/loans/LoansIntegrationTest.java
core-contracts/Loans/src/main/java/network/balanced/score/core/loans/LoansImpl.java
core-contracts/Loans/src/main/java/network/balanced/score/core/loans/positions/Position.java
core-contracts/Loans/src/test/java/network/balanced/score/core/loans/LoansTest.java
core-contracts/Loans/src/test/java/network/balanced/score/core/loans/LoansTestBase.java
core-contracts/Reserve/src/intTest/java/network/balanced/score/core/reserve/ReserveIntegrationTest.java
score-lib/src/main/java/network/balanced/score/lib/interfaces/Governance.java

Change adding of collateral to votes in test
Bugfix in balancedOracle

add addCollateral to voteActions

---

core-contracts/Dex/src/main/java/network/balanced/score/core/dex/AbstractDex.java
core-contracts/Dex/src/test/java/network/balanced/score/core/dex/DexTestCore.java

Converted balnFees in terms of quote tokens and sent it to fee handler

balnFees only in quote token for dex exchange

---

token-contracts/BalancedDollar/src/main/java/network/balanced/score/tokens/balanceddollar/BalancedDollarImpl.java
token-contracts/BalancedDollar/src/test/java/network/balanced/score/tokens/balanceddollar/BalancedDollarImplTest.java
token-contracts/Sicx/src/main/java/network/balanced/score/tokens/sicx/SicxImpl.java
token-contracts/Sicx/src/test/java/network/balanced/score/tokens/sicx/SicxImplTest.java

* Add blacklist to sICX and bnUSD
* Add govTransfer to sICX
* Default blacklist is added but temporay until verified

Recovery updated to enbale re-enable of balanced

---

core-contracts/Loans/src/main/java/network/balanced/score/core/loans/LoansImpl.java
core-contracts/Loans/src/main/java/network/balanced/score/core/loans/debt/DebtDB.java
core-contracts/Loans/src/test/java/network/balanced/score/core/loans/LoansTest.java
score-lib/src/main/java/network/balanced/score/lib/utils/Versions.java

Add method to read from linked list
re-Add null check for depositAndBorrow.

Improve loans read methods

---

core-contracts/DAOfund/src/intTest/java/network/balanced/score/core/daofund/DaofundIntegrationTest.java
core-contracts/DAOfund/src/main/java/network/balanced/score/core/daofund/DAOfundImpl.java
core-contracts/DAOfund/src/main/java/network/balanced/score/core/daofund/POLManager.java
core-contracts/DAOfund/src/test/java/network/balanced/score/core/daofund/DAOfundImplTest.java
score-lib/src/main/java/network/balanced/score/lib/interfaces/DAOfund.java
score-lib/src/main/java/network/balanced/score/lib/utils/Versions.java

Split supply POL method to only supply to dex. add method to unstake lp token. Add permission for staking tokens

feat: Split supply and stake logic for protocol owned liquidity

---

core-contracts/DAOfund/src/intTest/java/network/balanced/score/core/daofund/DaofundIntegrationTest.java
core-contracts/DAOfund/src/main/java/network/balanced/score/core/daofund/POLManager.java
core-contracts/DAOfund/src/test/java/network/balanced/score/core/daofund/DAOfundImplTest.java
core-contracts/Dex/src/intTest/java/network/balanced/score/core/dex/DexIntegrationTest.java
core-contracts/Dex/src/intTest/java/network/balanced/score/core/dex/NonStakedLPRewardsTest.java
core-contracts/Loans/src/intTest/java/network/balanced/score/core/loans/LoansIntegrationTest.java
core-contracts/Loans/src/main/java/network/balanced/score/core/loans/debt/DebtDB.java
core-contracts/Reserve/src/intTest/java/network/balanced/score/core/reserve/ReserveIntegrationTest.java
core-contracts/Rewards/src/intTest/java/network/balanced/score/core/rewards/RewardsIntegrationTest.java
core-contracts/Rewards/src/main/java/network/balanced/score/core/rewards/DataSourceImpl.java
core-contracts/Rewards/src/main/java/network/balanced/score/core/rewards/RewardsImpl.java
core-contracts/Rewards/src/test/java/network/balanced/score/core/rewards/RewardsTestBase.java
core-contracts/Rewards/src/test/java/network/balanced/score/core/rewards/RewardsTestRewards.java
score-lib/src/main/java/network/balanced/score/lib/interfaces/Rewards.java
score-lib/src/main/java/network/balanced/score/lib/utils/AddressVarDB.java
score-lib/src/main/java/network/balanced/score/lib/utils/BranchedAddressDictDB.java
score-lib/src/test/java/network/balanced/score/lib/utils/AddressDBMigrations.java
score-lib/src/test/java/network/balanced/score/lib/utils/contracts/DBMigrationsContract.java
test-lib/src/main/java/network/balanced/score/lib/test/integration/Balanced.java
token-contracts/bBaln/src/intTest/java/network/balanced/score/tokens/BoostedBalnGeneralIntegrationTest.java
token-contracts/bBaln/src/intTest/java/network/balanced/score/tokens/BoostedBalnIncreaseTimeTest.java

Migrate rewards positions to be String Addresses

---

core-contracts/Loans/src/intTest/java/network/balanced/score/core/loans/LoansIntegrationTestMigration.java
core-contracts/Loans/src/main/java/network/balanced/score/core/loans/LoansImpl.java
core-contracts/Loans/src/main/java/network/balanced/score/core/loans/linkedlist/LinkedListDB.java
core-contracts/Loans/src/main/java/network/balanced/score/core/loans/positions/Position.java
score-lib/src/main/java/network/balanced/score/lib/utils/Versions.java

Add method to fix invalid positions

fix: Use absolute loan amount when calculating new debt share.

---

score-lib/src/main/java/network/balanced/score/lib/interfaces/SpokeAssetManager.java
score-lib/src/main/java/network/balanced/score/lib/interfaces/XCallManager.java
spoke-contracts/SpokeAssetManager/src/main/java/network/balanced/score/spoke/asset/manager/SpokeAssetManagerImpl.java
spoke-contracts/SpokeBalancedDollar/src/main/java/network/balanced/score/spoke/bnusd/SpokeBalancedDollarImpl.java
spoke-contracts/SpokeBalancedDollar/src/test/java/network/balanced/score/spoke/bnusd/SpokeBalancedDollarTest.java
spoke-contracts/SpokeXCallManager/src/test/java/network/balanced/score/spoke/xcall/manager/SpokeXCallManagerTest.java

Remove token handling logic for this release, remove unsused imports and fix warnings

fix: Havh Internal Audit fixes

---

core-contracts/AssetManager/src/main/java/network/balanced/score/core/asset/manager/AssetManagerImpl.java
core-contracts/AssetManager/src/test/java/network/balanced/score/core/asset/manager/AssetManagerTest.java
score-lib/src/main/java/network/balanced/score/lib/utils/Versions.java

deposit amount validation while withdraw on asset manager to assure remaining deposited amount not negative

deposit amount validation while withdraw on asset manager

---

core-contracts/DAOfund/src/main/java/network/balanced/score/core/daofund/DAOfundImpl.java
score-lib/src/main/java/network/balanced/score/lib/structs/ProtocolConfig.java
score-lib/src/main/java/network/balanced/score/lib/utils/XCallUtils.java
util-contracts/XCallManager/src/main/java/network/balanced/score/util/xcall/manager/XCallManagerImpl.java

Also allow unchecked rollbacks

feat: Use protocols when estimating daofund xCall fees 

---

score-lib/src/main/java/network/balanced/score/lib/interfaces/tokens/HSP20.java
score-lib/src/main/java/network/balanced/score/lib/tokens/IRC2HSP20.java
score-lib/src/main/java/network/balanced/score/lib/utils/Versions.java
spoke-contracts/SpokeAssetManager/src/main/java/network/balanced/score/spoke/asset/manager/SpokeAssetManagerImpl.java
spoke-contracts/SpokeAssetManager/src/test/java/network/balanced/score/spoke/asset/manager/SpokeAssetManagerTest.java
spoke-contracts/SpokeBalancedDollar/src/main/java/network/balanced/score/spoke/bnusd/SpokeBalancedDollarImpl.java
spoke-contracts/SpokeXCallManager/src/main/java/network/balanced/score/spoke/xcall/manager/SpokeXCallManagerImpl.java
spoke-contracts/SpokeXCallManager/src/test/java/network/balanced/score/spoke/xcall/manager/SpokeXCallManagerTest.java

435 follow hsp20 token standard on havah contracts

---

core-contracts/Loans/src/intTest/java/network/balanced/score/core/loans/LoansIntegrationTest.java
core-contracts/Loans/src/main/java/network/balanced/score/core/loans/LoansImpl.java
core-contracts/Loans/src/test/java/network/balanced/score/core/loans/LoansTestCrosschain.java
score-lib/src/main/java/network/balanced/score/lib/interfaces/Loans.java

feat: Add option for xWithdraw to withdraw to another address

---

core-contracts/Loans/src/main/java/network/balanced/score/core/loans/LoansImpl.java
core-contracts/Loans/src/test/java/network/balanced/score/core/loans/LoansTest.java

Add parameterized tests to soft liquidations

---

score-lib/src/main/java/network/balanced/score/lib/utils/Versions.java
test-lib/src/main/java/network/balanced/score/lib/test/integration/Balanced.java
token-contracts/BalancedToken/build.gradle
token-contracts/BalancedToken/src/main/java/network/balanced/score/tokens/balancedtoken/BalancedTokenImpl.java
token-contracts/BalancedToken/src/main/java/network/balanced/score/tokens/balancedtoken/BalancedTokenVariables.java
token-contracts/BalancedToken/src/main/java/network/balanced/score/tokens/balancedtoken/Constants.java
token-contracts/BalancedToken/src/test/java/network/balanced/score/tokens/balancedtoken/BalancedTokenImplTest.java
token-contracts/Sicx/build.gradle
token-contracts/Sicx/src/main/java/network/balanced/score/tokens/sicx/SicxImpl.java
token-contracts/Sicx/src/test/java/network/balanced/score/tokens/sicx/SicxImplTest.java

feat: sicx/balan token crosschain

---

score-lib/src/main/java/network/balanced/score/lib/tokens/HubTokenImpl.java

fix: quer spoke limit

---

score-lib/src/main/java/network/balanced/score/lib/utils/Versions.java

```bash
fix: sicx version updated 
```
```bash
```

fix: sicx version updated

---

core-contracts/Multicall/src/main/java/network/balanced/score/core/multicall/Multicall.java

fix: network address type issue fixed
